"""Version identifiers embedded in public artifacts."""

ENGINE_VERSION = "1.0.0"
CONTROLLER_API_VERSION = 1
SCENARIO_GENERATOR_VERSION = 1
REPLAY_VERSION = 1
CALIBRATION_VERSION = 2
TOURNAMENT_FORMAT_VERSION = 1
